version = 1

# Not using test_patterns because it still marks
# self in pytest classes as errors
exclude_patterns = ["tests/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
